version: '3.5'

services:
  dist:
    build: ./
    container_name: 'antbear-ui-dist'
    volumes:
      - dist:/app/dist

  nginx:
    image: nginx:1.16.1
    ports:
      - 8000:8000
    container_name: 'antbear-ui-nginx'
    restart: unless-stopped
    volumes:
      - dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  dist:
